In [1]:
#importing the library
import numpy as np

In [2]:
#How numpy is different
A=[[10,20,30],[40,50,60]]
B=np.array(A)
print('A:',A)
print('B:',B)

A: [[10, 20, 30], [40, 50, 60]]
B: [[10 20 30]
 [40 50 60]]


In [3]:
#Displaying the datatype of numpy arrays
C=np.array([10,20,30])
print('Datatype of C:',C.dtype)
D=np.array([10.2,20.5,50.92])
print('Datatype of D:',D.dtype)

Datatype of C: int32
Datatype of D: float64


In [4]:
#display the dimension of array( axes in array)
print('Dimension of B',B.ndim)
print('Dimension of C',C.ndim)

Dimension of B 2
Dimension of C 1


In [5]:
#displaying the shape(no of rows and coloums)
print('Shape of Array B:',B.shape)
print('Shape of Array C:',C.shape)

Shape of Array B: (2, 3)
Shape of Array C: (3,)


In [6]:
#reshaping the arrays
print("Before reshaping B:",B)
B = B.reshape(3,2)
print("\nAfter reshaping B:",B)
print("\n\nBefore reshaping C:",C)
C = C.reshape(1,3)
print("\nAfter reshaping C:",C)

Before reshaping B: [[10 20 30]
 [40 50 60]]

After reshaping B: [[10 20]
 [30 40]
 [50 60]]


Before reshaping C: [10 20 30]

After reshaping C: [[10 20 30]]


In [8]:
#copy operation
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=arr1.copy()
arr1[1][1]=10
print('Array 1:\n',arr1)
print('\nArray 2:\n',arr2)

Array 1:
 [[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]

Array 2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
#view operation
arr3 = arr1.view()
print('Array 1:\n',arr1)
print('\nArray 3:\n',arr3)

Array 1:
 [[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]

Array 3:
 [[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]


In [10]:
#difference between copy and view
arr4 = arr1.view()
arr1[1][0]=5
print('Array 1:\n',arr1)
print('\nArray 4:\n',arr4)

Array 1:
 [[ 1  2  3]
 [ 5 10  6]
 [ 7  8  9]]

Array 4:
 [[ 1  2  3]
 [ 5 10  6]
 [ 7  8  9]]


In [11]:
#indexing and slicing
a = np.array([[11,12,13],[14,15,16]])
a

array([[11, 12, 13],
       [14, 15, 16]])

In [12]:
print('a[1,1]:',a[1,1]) #indexing
print('\na[0,-1]',a[0,-1]) #last item of first row

a[1,1]: 15

a[0,-1] 13


In [13]:
#slicing the first row
print('a[0,1:]',a[0,1:])
#missing indices are treated as complete slices
print('\na[1]:',a[1])
print('\na[1,:]',a[1,:])

a[0,1:] [12 13]

a[1]: [14 15 16]

a[1,:] [14 15 16]
